---
spec_version: 1
kind: blueprint

metadata:
  description: >
    A simple multi-tier application deployed on a single Azure VM.
clouds:
  - azure: westeurope

# These are the blueprint parameters and their default values.
# The values can be changed when creating a sandbox based on this
# blueprint.
inputs:
  - DB_USER: root  # Used to define the db admin account
  - DB_PASS:
      display_style: masked
      description: please set the root database password
      default_value: 12345
  # Used to define the db admin password
  - DB_NAME: demo_db  # DB_NAME - a target database name

# These are the applications that will be deployed in this blueprint
applications:
  - mysql:  # One instance of mysql (see: applications/mysql/mysql.yaml)
      target: all-in-one
      input_values:
        - DB_USER: $DB_USER  # Assign values from the app inputs
        - DB_PASS: $DB_PASS
        - DB_NAME: $DB_NAME
  # One instance of java-spring-website
  # (see: applications/java-spring-website/java-spring-website.yaml)
  - java-spring-website:
      target: all-in-one
      input_values:
        - DB_USER: $DB_USER
        - DB_PASS: $DB_PASS
        - DB_NAME: $DB_NAME
        - DB_HOSTNAME: $colony.applications.mysql.dns
      # The website depends on MySQL and will start deploying only when
      # the database is ready
      depends_on:
        - mysql
