---
spec_version: 1
kind: blueprint

metadata:
  description: >
    Java application with a managed Azure database deployed with TerraForm.
clouds:
  - azure: westeurope

# These are the blueprint parameters and their default values.
# The values can be changed when creating a sandbox based on this
# blueprint.
inputs:
  - DB_USER: colony  # Used to define the db admin account
  - DB_PASS:
      display_style: masked
      description: >
        Database server password must contain from 8 to 128 characters.
        Your password must contain characters from
        three of the following categories:
        English uppercase letters, English lowercase letters, numbers (0-9),
        and non-alphanumeric characters (!, $, #, %, and so on)
      default_value: sv4YPTPs7fN&
  # Used to define the db admin password
  - DB_NAME: demo_db  # DB_NAME - a target database name
  - MANAGED_IDENTITY
# These are the applications that will be deployed in this blueprint
applications:
  # One instance of java-spring-website
  # (see: applications/java-spring-website/java-spring-website.yaml)
  - java-spring-website:
      instances: 1
      input_values:
        - DB_HOSTNAME: $colony.services.azure-mysql.outputs.server_name
        - DB_USER: $colony.services.azure-mysql.outputs.server_admin_login_name
        - USE_SSL: true
        - DB_PASS: $DB_PASS
        - DB_NAME: $DB_NAME
      # The website depends on MySQL and will start deploying only when
      # the database is ready
      depends_on:
        - azure-mysql
services:
  # Instance of azure database mysql
  # (see: services/azure-mysql/azure-mysql.yaml)
  - azure-mysql:
      input_values:
        - DB_NAME: $DB_NAME
        - DB_USER: $DB_USER
        - DB_PASS: $DB_PASS
        - SANDBOX_ID: $colony.environment.id
        - MANAGED_IDENTITY: $MANAGED_IDENTITY
debugging:
  bastion_availability: enabled-on
