---
spec_version: 1
kind: blueprint

metadata:
  description: >
    Java application with a managed RDS database deployed with TerraForm.

clouds:
  - AWS: eu-west-1

# These are the blueprint parameters and their default values.
# The values can be changed when creating a sandbox based on this
# blueprint.
inputs:
  - DB_USER: root  # Used to define the db admin account
  - DB_PASS:
      display_style: masked
      description: please set the root database password
      default_value: Colony!123
  # Used to define the db admin password
  - DB_NAME: demo_db  # DB_NAME - a target database name

# These are the applications that will be deployed in this blueprint
applications:
  # One instance of java-spring-website
  # (see: applications/java-spring-website/java-spring-website.yaml)
  - java-spring-website:
      instances: 1
      input_values:
        - DB_USER: $DB_USER
        - DB_PASS: $DB_PASS
        - DB_NAME: $DB_NAME
        # DNS name output from the RDS service
        - DB_HOSTNAME: $colony.services.rds-mysql.outputs.hostname
      # The website depends on MySQL and will start deploying only when
      # the database is ready
      depends_on:
        - rds-mysql
services:
  - rds-mysql:  # One instance of mysql (see: services/rds-mysql/rds-mysql.yaml)
      input_values:
        - DB_NAME: $DB_NAME
        - DB_USER: $DB_USER
        - DB_PASS: $DB_PASS
        - SANDBOX_ID: $colony.environment.id
        - VPC_ID: $colony.environment.virtual_network_id  # Sandbox VPC Id
debugging:
  bastion_availability: enabled-on
